permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Mythological Creature Market"
  description: |
    An online vendor of fine mythological beasts.
  font_url: "https://fonts.googleapis.com/css?family=Almendra+SC|Aref+Ruqaa:400,700"
  colors:
    background: "--color-primary-light"
    accent: "--color-accent"
  rationales:
    typefaces.primary: |
      It looks rustic and is legible. It is used for all body copy, the navigation, the footer, and the site directory.
    typefaces.secondary: |
      It is an interesting display typeface with a Medieval style. It is used for all headings.
    colors.primary: |
      This deep brown colour helps reflect Medieval style and also emulates the brown fur of potential creatures. It is used as a background to the page directory as well as the footer.
    colors.secondary: |
      This medium brown looks like old paper which fits the theme. It is the background colour of the navigation.
  layouts:
    default: |
      The default layout should be used for every page as it includes the header and footer.
collections:
  products:
    output: true

defaults:
  - scope:
      path: _products
    values:
      layout: product
