title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to overuse buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
    background: "--color-secondary"
  ghost:
    title: "Ghost"
    description: |
      The ghost button is specifically for banners, where it will be placed in front of busy images.
  light:
    title: "Light"
    description: |
      Similar to the default button but with a lighter colour. Can be used on dark backgrounds.
  shoppingcart:
    title: "shoppingcart"
    description: |
      The shopping cart button is part of the navigation at the top of the page. Only use it in this instance.
  hamburger:
    title: "hamburger"
    description: |
      The hamburger button is part of the navigation at the top of the page. Only use it in this instance. It toggles a drop down navigation on small screen sizes.
  settings:
    title: "settings"
    description: |
      The settings button is part of the navigation at the top of the page. Only use it in this instance. The button allows users to sign in to the website and change their personal settings.

# The code from this point forward does not work

title: "Cards"
description: |
  You can use cards on the product page to establish what merchandise is available.

cards:
  creature-card:
    title: "Creature Card"
    description: |
      This card is used on the products page to display what categories of creatures are available.

title: "forms"
description: |
  Forms are used in a variety of different situations where users need to input information.

forms:
  checkout-form:
    title: "Checkout Form"
    description: |
      The checkout form will be used when users are prepared to buy the product.
  mailinglist-form:
    title: "Mailing List Form"
    description: |
      The mailing list form can be toggled when users choose to join the mailing list from the signup page.
  signin-form:
    title: "Sign In Form"
    description: |
      The sign in form can be toggled from the navigation.
  signup-form:
    title: "Sign Up Form"
    description: |
      The sign in form can be toggled from the navigation.
