title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to overuse buttons because they should be the primary call-to-action for a screen.
