title: "Sections"
description: |
  These sections are scattered throughout different pages of the website.

patterns:
  homepage-welcome:
    title: "Welcome Text"
    description: |
      This brief description on the homepage gives users a short glimpse into what the company sells.
  testimonial-section:
    title: "Sven's Testimonial"
    description: |
    This testimonial appears on the homepage alongside the brief welcome text section.
  productpage-text:
    title: "Product Page Text"
    description: |
    This information is displayed on the page where one views the specific creature they are interested in purchasing.
  products-intro-text:
    title: "Products Intro Text"
    description: |
    This information appears on the product page as an introduction to the different species.
