patterns:
  homepagebanner:
    title: "Home page banner"
    description: This banner is used on the home page only. |
    fields:
      - name: heading
        type: string
        example: "The Creature Collection"
      - name: text
        type: string
        example: "Browse our collection of feisty beasts."
      - name: button_text
        type: string
        example: "See Collection"
        required: false
      - name: button_text
        type: string
        example: "/products/"
        required: false
