patterns:
  homepagebanner:
    fields:
      - name: heading
        type: string
        example: "The Creature Collection"
      - name: text
        type: string
        example: "Browse our collection of feisty beasts."
