patterns:
  homepagebanner:
    fields:
      - name: heading
        type: string
        example: "The Griffin Collection"
      - name: text
        type: string
        example: "Browse our selection of these feisty beasts."
